notifications:
  email: false
sudo: false

language: python
python:
  - '3.5'

services:
  - postgresql
addons:
  postgresql: '9.6'

env:
  - SQLALCHEMY_DATABASE_URI='postgresql+psycopg2://postgres@localhost/asclepias' EXTRAS='[tests,postgres]'

before_script:
  - psql -c 'create database asclepias;' -U postgres
install:
  - travis_retry pip install -e .${EXTRAS}
script:
  - py.test tests
