notifications:
  email: false
sudo: false

language: python
python:
  - '3.5'
  - '3.6'

services:
  - postgresql
addons:
  postgresql: '9.6'

env:
# TODO: SQLite has issues with cascading
# - SQLALCHEMY_DATABASE_URI='sqlite:///asclepias.db' EXTRAS='[tests]'
  - SQLALCHEMY_DATABASE_URI='postgresql+psycopg2://postgres@localhost/asclepias' EXTRAS='[tests,postgres]'

before_script:
  - psql -c 'create database asclepias;' -U postgres
install:
  - travis_retry pip install -e .${EXTRAS}
script:
  - py.test tests
