notifications:
  email: false
sudo: false

language: python
python:
  - '3.5'

services:
  - postgresql
addons:
  postgresql: '9.6'

env:
  - SQLALCHEMY_DATABASE_URI='postgresql+psycopg2://postgres@localhost/asclepias' EXTRAS='[tests,postgres]'

before_install:
  - mkdir /tmp/elasticsearch
  - "wget -O - https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.7.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1"
  - "/tmp/elasticsearch/bin/plugin install -b mapper-attachments"
  - "/tmp/elasticsearch/bin/elasticsearch > /tmp/local-es.log &"

before_script:
  - psql -c 'create database asclepias;' -U postgres
  - sleep 10
  - curl http://127.0.0.1:9200 && echo "Elasticsearch is up!" || cat /tmp/local-es.log

  install:
  - travis_retry pip install -e .${EXTRAS}

  script:
  - py.test tests
